### ISSUE TITLE
netbox-python-0.1.7 wheel from pypi version detection is broken

### ISSUE THREAD

**Issue by Urth** [netbox-community/netbox-python#25]
### NetBox Python version

0.1.7

### NetBox version

3.6.6

### Python version

3.11

### Steps to Reproduce

```sh
$ python -m venv tmp
$ . tmp/bin/activate
$ pip install netbox-python==0.1.7
Collecting netbox-python==0.1.7
  Using cached netbox_python-0.1.7-py3-none-any.whl (17 kB)
Collecting requests<3.0,>=2.20.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, netbox-python
Successfully installed certifi-2023.11.17 charset-normalizer-3.3.2 idna-3.6 netbox-python-0.1.7 requests-2.31.0 urllib3-2.1.0

$ python
Python 3.11.4 (main, Dec  7 2023, 15:43:41) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netbox_python
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harm/tmp/lib/python3.11/site-packages/netbox_python/__init__.py", line 6, in <module>
    __version__ = version("0.1.7")
                  ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for 0.1.7
>>> from importlib.metadata import version
>>> version('netbox_python')
'0.1.7'

$ grep version /home/harm/tmp/lib/python3.11/site-packages/netbox_python/__init__.py
from importlib.metadata import version
__version__ = version("0.1.7")
```

### Expected Behavior

The module import should not fail on version detection.

### Observed Behavior

The release has replaced the dynamic `version(__name__)` with a hardcoded `version("0.1.7")`

**Comment by arthanson** [comment]
did a quick 0.1.8 release to fix.
