### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for 0.1.7

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [netbox-community/netbox-python#26]
### NetBox Python version

v0.1.7

### NetBox version

v3.6.7

### Python version

3.10

### Steps to Reproduce

Install `netbox-python==0.1.7`, then try to import the module into python.

### Expected Behavior

Like in `v0.1.6`, I expect it to import with no issue:
```
import netbox_python
```

### Observed Behavior

I see this error:
```
>>> import netbox_python

Traceback (most recent call last):

File "<stdin>", line 1, in <module>

File "/home/path/venv/lib/python3.10/site-packages/netbox_python/__init__.py", line 6, in <module>

__version__ = version("0.1.7")

File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version

return distribution(distribution_name).version

File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution

return Distribution.from_name(distribution_name)

File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name

raise PackageNotFoundError(name)

importlib.metadata.PackageNotFoundError: No package metadata was found for 0.1.7
```

**Comment by arthanson** [comment]
Did a quick 0.1.8 release to fix.
